sudo: required
dist: trusty
services: docker
env:
- PROTOBUF_VER=3.5.0
- GRPCIO_VER=1.7.0
- GPGKEY=84B8A307

jobs:
  include:
  - stage: build dependencies
    os: linux
    env:
    - PLATFORM=xenial
    script:
    - "./travis_build.sh"
    - "./push_to_git.sh"
  - stage: build dependencies
    os: linux
    env:
    - PLATFORM=stretch
    script:
    - "./travis_build.sh"
    - "./push_to_git.sh"
  - stage: merge buildfiles from architectures to a single Git branch
    os: linux
    env: 
    script: "./merge_git.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_092fa53f157b_key -iv $encrypted_092fa53f157b_iv
  -in keys.tar.enc -out keys.tar -d
