sudo: required
dist: trusty
services: docker
env:
- PROTOBUF_VER=3.5.0
- GRPCIO_VER=1.7.0
- GPGKEY=84B8A307
jobs:
  include:
  - stage: build dependencies
    os: linux
    env:
    - PLATFORM=xenial
    script:
    - "./travis_build.sh"
    deploy:
      provider: script
      skip_cleanup: true
      script: "./push_to_git.sh"
      on:
        all_branches: true
  - stage: build dependencies
    os: linux
    env:
    - PLATFORM=stretch
    script:
    - "./travis_build.sh"
    deploy:
      provider: script
      skip_cleanup: true
      script: "./push_to_git.sh"
      on:
        all_branches: true
  - stage: merge buildfiles from architectures to a single Git branch
    os: linux
    script:
    - echo "merging dependency .debs to ghpages"
    deploy:
      provider: script
      skip_cleanup: true
      script: "./merge_git.sh"
      on:
        all_branches: true
before_install:
- openssl aes-256-cbc -K $encrypted_092fa53f157b_key -iv $encrypted_092fa53f157b_iv
  -in keys.tar.enc -out keys.tar -d
